### ISSUE TITLE
Script doesn't handle spaces in the CA name properly

### ISSUE THREAD

**Issue by elijsearle** [system32blog/blog#71]
**Describe the bug**
If the CA name has spaces in it, the script improperly removes it.

**To Reproduce**
Use the script on a CA with spaces in the name.  The resulting string creates X509: text with an incorrect CA name.

**Expected behavior**
Should properly account for spaces and/or commas in the CA Issuer Name, OU, or DC

**Screenshots**

**Additional context**
Line  $CACertSubject = (Reverse-CertificateIssuer -CertIssuer $CAs.$($cert.ConfigString).Certificate.Subject).Replace(" ","") should read
 $CACertSubject = (Reverse-CertificateIssuer -CertIssuer $CAs.$($cert.ConfigString).Certificate.Subject).Replace(" ,",",") or in case the CA Name has a comma in it (which I believe it can)
 $CACertSubject = (Reverse-CertificateIssuer -CertIssuer $CAs.$($cert.ConfigString).Certificate.Subject).Replace(" DC",",DC")
 Or in the example at https://playbooks.idmanagement.gov/piv/network/account/ which shows some CA OU containing spaces as well
 $CACertSubject = ((Reverse-CertificateIssuer -CertIssuer $CAs.$($cert.ConfigString).Certificate.Subject).Replace(" DC",",DC")).Replace(" OU",",OU")

In my case the $CACertSubject = (Reverse-CertificateIssuer -CertIssuer $CAs.$($cert.ConfigString).Certificate.Subject).Replace(" DC",",DC") worked for me.

**Comment by RobinBeismann** [comment]
Alright, I'm now properly replacing the DC, OU, CN and O Fields in it. Thanks for reporting!
